# Spring settings
spring:
    profiles.active: dev

    kafka:
        bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9092,127.0.0.1:9092
        consumer:
            enable-auto-commit: true
            auto-commit-interval: 100
            group-id: kong-1
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
            properties:
                session.timeout.ms: 15000
        producer:
            retries: 0
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
            properties:
                linger.ms: 1


kafkaMQ:
    data_number: ${DATA_NUMBER}
    thread_number: ${THREAD_NUMBER}